server:
    # Базовые параметры
    num-threads: 1
    num-queries-per-thread: 4096

    # Демонизация
    do-daemonize: yes
    username: "unbound"
    chroot: ""
    directory: "/etc/unbound"

#    module-config: "ipsecmod validator iterator"
    module-config: "iterator"
