server:
        # Защитные механизмы
        harden-glue: yes
        harden-below-nxdomain: yes

        use-caps-for-id: no

        #DoDOS protection
        #ratelimit: 500
        #ratelimit-slabs: 8
        #ratelimit-factor: 50

        unwanted-reply-threshold: 10000     # ограничивает количество "ненужных" записей в DNS-ответе
