server:
        # увеличить количество слэбов (для многопоточности) = num-thread
        msg-cache-slabs: 1
        rrset-cache-slabs: 1
        infra-cache-slabs: 1
        key-cache-slabs: 1

        # Включить возврат просроченных записей
        serve-expired: yes

        # Максимальное время, в течение которого можно возвращать expired-записи (4 часа)
        serve-expired-ttl: 14400

        # Блокировка типов запросов, нагружающих сервер
        qname-minimisation: yes            # Снижает утечку информации
        minimal-responses: yes
        rrset-roundrobin: yes              # круговая выдача

        # Потоки
        msg-cache-size: 50m
        rrset-cache-size: 100m
        infra-cache-numhosts: 20000        # метаданные серверов

        # TTL-настройки
        cache-min-ttl: 300                 # Минимальное время кэширования (60 сек)
        cache-max-ttl: 720                 # Максимальное (1 час, для стабильных записей)
        cache-max-negative-ttl: 300        # Максимальное время кеширования отрицательных ответов (NXDOMAIN)
        infra-host-ttl: 300                # TTL для инфраструктурных записей (5 мин)
        infra-lame-ttl: 120                # TTL для проблемных серверов (2 мин)

        # Оптимизация памяти
        prefetch: yes                      # Предзагрузка популярных записей

        deny-any: yes                      # Блокировать запросы ANY (RFC 8482)
