create route_vpn hash:net family inet hashsize 1024 maxelem 2655360 comment bucketsize 12 initval 0xd73d9b39
add route_vpn 162.159.140.0/24 comment "api.openai.com-1"
add route_vpn 13.64.0.0/11 comment "cdn.openai.com-1"
add route_vpn 91.105.192.0/23 comment "telegram-1"
add route_vpn 157.240.253.0/24 comment "whatsapp-5"
add route_vpn 8.47.69.0/24 comment "chatgpt.com-5"
add route_vpn 159.148.147.0/24 comment "forum.mikrotik.com"
add route_vpn 91.108.12.0/22 comment "telegram-4"
add route_vpn 149.154.160.0/20 comment "telegram-9"
add route_vpn 172.66.0.0/24 comment "api.openai.com-2"
add route_vpn 172.64.155.0/24 comment "chatgpt.com-2"
add route_vpn 15.197.210.0/24 comment "whatsapp-4"
add route_vpn 13.104.0.0/14 comment "cdn.openai.com-3"
add route_vpn 3.120.252.118 comment "www.saveris.net-1"
add route_vpn 18.159.127.189 comment "www.saveris.net-3"
add route_vpn 13.96.0.0/13 comment "cdn.openai.com-2"
add route_vpn 162.213.33.0/24 comment "pool.sks-keyservers.net"
add route_vpn 104.18.32.0/24 comment "chatgpt.com-1"
add route_vpn 65.108.3.114 comment "www.postfix.org"
add route_vpn 157.240.0.0/24 comment "whatsapp-1"
add route_vpn 141.148.50.0/24 comment "forums.zimbra.org"
add route_vpn 91.108.56.0/22 comment "telegram-7"
add route_vpn 95.161.64.0/20 comment "telegram-8"
add route_vpn 163.172.104.231 comment "icom.museum"
add route_vpn 104.18.33.0/24 comment "platform.openai.com-1"
add route_vpn 104.18.41.0/24 comment "chatgpt.com-6"
add route_vpn 185.125.188.0/24 comment "keyserver.ubuntu.com"
add route_vpn 185.76.151.0/24 comment "telegram-10"
add route_vpn 157.240.0.0/16 comment "facebook-1"
add route_vpn 3.33.252.0/24 comment "whatsapp-3"
add route_vpn 108.177.0.0/17 comment "chatgpt.com-8"
add route_vpn 91.108.16.0/22 comment "telegram-5"
add route_vpn 18.9.60.0/24 comment "pgp.mit.edu"
add route_vpn 172.64.154.0/24 comment "platform.openai.com-2"
add route_vpn 104.16.102.0/23 comment "canva"
add route_vpn 157.240.205.0/24 comment "whatsapp-2"
add route_vpn 8.6.112.0/24 comment "chatgpt.com-4"
add route_vpn 57.144.249.0/24 comment "whatsapp-7"
add route_vpn 91.108.8.0/22 comment "telegram-3"
add route_vpn 104.18.35.0/24 comment "chatgpt.com-7"
add route_vpn 172.64.146.0/24 comment "auth.openai.com"
add route_vpn 57.144.223.0/24 comment "whatsapp-6"
add route_vpn 91.108.4.0/22 comment "telegram-2"
add route_vpn 57.144.0.0/16 comment "facebook-2"
add route_vpn 188.114.98.0/23 comment "chatgpt.com-3"
add route_vpn 91.108.20.0/22 comment "telegram-6"
