create route_youtube hash:net family inet hashsize 1024 maxelem 2655360 comment bucketsize 12 initval 0x02ccf235
add route_youtube 216.58.192.0/19 comment "ytimg.com"
add route_youtube 209.85.128.0/17 comment "googlevideo"
add route_youtube 78.37.65.0/24 comment "RU-RT-NW-GOOGLE"
add route_youtube 188.43.60.0/23 comment "GOOGLE-TTK-NET1"
add route_youtube 188.43.66.0/23 comment "GOOGLE-TTK-NET3"
add route_youtube 108.177.0.0/17 comment "www.youtube.com"
add route_youtube 188.43.64.0/23 comment "GOOGLE-TTK-NET2"
add route_youtube 142.250.0.0/15 comment "youtube 1e100.net"
add route_youtube 192.178.0.0/15 comment "youtube.com"
add route_youtube 64.233.160.0/19 comment "youtube 1e100.net"
add route_youtube 173.194.0.0/16 comment "youtube 1e100.net"
add route_youtube 172.217.0.0/16 comment "youtube 1e100.net"
add route_youtube 74.125.0.0/16 comment "youtube 1e100.net"
add route_youtube 164.215.0.0/16 comment "googlevideo.com"
add route_youtube 188.43.68.0/23 comment "GOOGLE-TTK-NET4"
