#server:
#     trust-anchor-signaling: yes
#     trusted-keys-file: /etc/unbound/keys.d/*.key
#     auto-trust-anchor-file: "/var/lib/unbound/root.key"

#     val-clean-additional: yes          # Удаляет из ответа дополнительные (additional) записи, не прошедшие DNSSEC-проверку.
#     val-permissive-mode: no            # Принимать невалидные ответы
#     val-log-level: 2                   # подробный лог

#     disable-dnssec-lame-check: yes     # Ускоряет проверку DNSSEC
#     aggressive-nsec: yes               # Уменьшает нагрузку при DNSSEC

#     harden-dnssec-stripped: yes        # Если Unbound ожидает DNSSEC-подписи (например, для домена, где они должны быть), но они отсутствуют — блокирует ответ.
#     harden-referral-path: yes          # Требует, чтобы весь путь делегирования (referral path) был подписан DNSSEC. Проверяет цепочку доверия от корня до домена.

#     prefetch-key: yes                  # Для DNSSEC
#     key-cache-size: 100m               # Кэш ключей DNSSEC
