server:
        port: 53
        outgoing-port-permit: 32768-65535
        outgoing-port-avoid: 0-32767

        interface-automatic: no

        do-not-query-localhost: no

        interface: 127.0.0.1
        interface: 10.1.2.1

        # Протоколы
        do-ip4: yes
        do-ip6: no
        do-udp: yes
        do-tcp: yes

        so-rcvbuf: 16m
        so-sndbuf: 16m
        so-reuseport: yes

        outgoing-range: 16384

        max-udp-size: 1472
